categories:
- Imaging
description: Galaxy-ME tool suite for Multiplex Tissue Imaging Analysis 
homepage_url: https://github.com/goeckslab/tools-mti
name: galaxy_me_suite
owner: goeckslab
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/master/suites/mcmicro_suite
type: repository_suite_definition 
