owner: perssond
remote_repository_url: https://github.com/ohsu-comp-bio/unmicst
categories: 
  - "CompBio Galaxy Wrappers"
repositories:
  unmicst:
    description: "Images can be preprocessed by inferring nuclei contours via a pretrained UNet model."
    include: 
      - unmicst.xml
      - macros.xml
      - batchUNet2DTMACycif.py
      - batchUNet2DtCycif.py
      - batchUnMicst.py
      - UnMicst.py
      - models/**
      - toolbox/**
