FROM python:3.11

RUN pip install \
    numpy==2.0.0 \
    pandas==2.2.2 \
    anndata==0.10.8 \
    tifffile==2024.7.2 \
    ome-types[lxml]==0.5.1.post1 \
    scikit-learn==1.5.1 \
    scikit-image==0.24.0
