{% set name = "opencv-python-headless" %}
{% set version = "4.5.1.48" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 1

requirements:
  build:
    - python
    - pip
    - numpy >=1.8.2
    - wheel >=0.26
  run:
    - python
    - numpy >=1.8.2

test:
  imports:
    - cv2

about:
  home: https://github.com/opencv/opencv
  summary: opencv python headless
  license: MIT

extra:
  recipe-maintainers:
    - ohsu-comp-bio

